name: Test

on:
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        default: ${{ github.ref_name }}

jobs:
  test:
    uses: ./.github/workflows/shared-test.yml